#!/bin/bash

if [ $1 -eq 1 ];then 
    rofi -no-config -no-lazy-grab -show drun -modi drun -theme ~/.config/bspwm/rofi/launcher1.rasi
elif [ $1 -eq 2 ];then 
    rofi -no-config -no-lazy-grab -show drun -modi drun -theme ~/.config/bspwm/rofi/launcher2.rasi
fi
