#!/bin/bash
# add your wallpaper to ~/.config/bspwm/wallpaper/ it will automatically show
rofi -modi Theme:$HOME/.config/bspwm/bin/setTheme -theme ~/.config/bspwm/rofi/network/network.rasi -show Theme
